import { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'english' | 'hindi' | 'bengali' | 'tamil' | 'telugu' | 'marathi' | 'gujarati' | 'kannada' | 'malayalam' | 'punjabi' | 'odia' | 'assamese';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  english: {
    portalName: "National Portal Of India",
    skillBridge: "SkillBridge",
    welcome: "Welcome to SkillBridge",
    description: "This is the main content area. The header above features the SkillBridge logo and branding. You can use the font size controls (-A A +A) in the header to adjust the text size across the website.",
    tryFontSize: "Try clicking the different A buttons in the top right of the header to see the font size change in real-time. This accessibility feature helps users adjust the text size to their preference.",
    sitemap: "Sitemap",
    skipToMain: "Skip to Main Content",
    aboutUs: "About Us",
    internshipOpportunities: "Internship Opportunities",
    mentorshipConnect: "Mentorship Connect",
    myMatches: "My Matches",
    profile: "Profile",
    cooperativeFederalism: "Cooperative Federalism",
    competitiveFederalism: "Competitive Federalism",
    keyInitiatives: "Key Initiatives",
    divisions: "Divisions",
    publications: "Publications",
    disclosuresRTI: "Disclosures & RTI",
    workAtNiti: "Work@NITI",
    quickLinks: "Quick Links",
    reportsAndStudies: "Reports & Studies",
    contactInfo: "Contact Information",
    governmentOfIndia: "Government of India",
    copyright: "Copyright",
    allRightsReserved: "All rights reserved",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    addressLine1: "Ministry of Skill Development & Entrepreneurship",
    addressLine2: "Shram Shakti Bhawan, New Delhi - 110001",
    email: "Email",
    phone: "Phone",
    report1: "National Skill Gap Analysis Report 2024",
    report2: "Digital Skills Framework for India",
    report3: "Industry Readiness Assessment Survey",
    report4: "Training Program Effectiveness Study",
    report5: "Employment Outcomes & Impact Report"
  },
  hindi: {
    portalName: "भारत का राष्ट्रीय पोर्टल",
    skillBridge: "स्किलब्रिज",
    welcome: "स्किलब्रिज में आपका स्वागत है",
    description: "यह मुख्य सामग्री क्षेत्र है। ऊपर दिया गया हेडर स्किलब्रिज लोगो और ब्रांडिंग को प्रदर्शित करता है। आप वेबसाइट पर टेक्स्ट साइज़ को समायोजित करने के लिए हेडर में फ़ॉन्ट साइज़ नियंत्रण (-A A +A) का उपयोग कर सकते हैं।",
    tryFontSize: "हेडर के टॉप राइट में विभिन्न A बटन पर क्लिक करके फ़ॉन्ट साइज़ को रियल-टाइम में बदलते हुए देखें। यह एक्सेसिबिलिटी फीचर उपयोगकर्ताओं को अपनी पसंद के अनुसार टेक्स्ट साइज़ समायोजित करने में मदद करती है।",
    sitemap: "साइटमैप",
    skipToMain: "मुख्य सामग्री पर जाएं",
    aboutUs: "हमारे बारे में",
    internshipOpportunities: "इंटर्नशिप के अवसर",
    mentorshipConnect: "मेंटरशिप कनेक्ट",
    myMatches: "मेरे मैच",
    profile: "प्रोफाइल",
    cooperativeFederalism: "सहकारी संघवाद",
    competitiveFederalism: "प्रतिस्पर्धी संघवाद",
    keyInitiatives: "मुख्य पहल",
    divisions: "विभाग",
    publications: "प्रकाशन",
    disclosuresRTI: "प्रकटीकरण और आरटीआई",
    workAtNiti: "नीति में काम",
    quickLinks: "त्वरित लिंक",
    reportsAndStudies: "रिपोर्ट और अध्ययन",
    contactInfo: "संपर्क जानकारी",
    governmentOfIndia: "भारत सरकार",
    copyright: "कॉपीराइट",
    allRightsReserved: "सभी अधिकार सुरक्षित",
    privacyPolicy: "गोपनीयता नीति",
    termsOfService: "सेवा की शर्तें",
    addressLine1: "कौशल विकास और उद्यमिता मंत्रालय",
    addressLine2: "श्रम शक्ति भवन, नई दिल्ली - 110001",
    email: "ईमेल",
    phone: "फोन",
    report1: "राष्ट्रीय कौशल अंतर विश्लेषण रिपोर्ट 2024",
    report2: "भारत के लिए डिजिटल कौशल ढांचा",
    report3: "उद्योग तैयारी मूल्यांकन सर्वेक्षण",
    report4: "प्रशिक्षण कार्यक्रम प्रभावशीलता अध्ययन",
    report5: "रोजगार परिणाम और प्रभाव रिपोर्ट"
  },
  bengali: {
    portalName: "ভারতের জাতীয় পোর্টাল",
    skillBridge: "স্কিল ব্রিজ",
    welcome: "স্কিল ব্রিজে স্বাগতম",
    description: "এটি মূল কন্টেন্ট এলাকা। উপরের হেডার স্কিল ব্রিজ লোগো এবং ব্র্যান্ডিং প্রদর্শন করে।",
    tryFontSize: "ফন্ট সাইজ পরিবর্তন দেখতে হেডারের টপ রাইটে বিভিন্ন A বোতামে ক্লিক করুন।",
    sitemap: "সাইটম্যাপ",
    skipToMain: "মূল বিষয়বস্তুতে যান",
    aboutUs: "আমাদের সম্পর্কে",
    internshipOpportunities: "ইন্টার্নশিপ অনুষ্ঠান",
    mentorshipConnect: "মেন্টরশিপ সংযোগ",
    myMatches: "আমার ম্যাচ",
    profile: "প্রোফাইল",
    cooperativeFederalism: "সমবায় যুক্তরাষ্ট্রবাদ",
    competitiveFederalism: "প্রতিযোগিতামূলক যুক্তরাষ্ট্রবাদ",
    keyInitiatives: "মূল উদ্যোগ",
    divisions: "বিভাগ",
    publications: "প্রকাশনা",
    disclosuresRTI: "প্রকাশ ও আরটিআই",
    workAtNiti: "নীতিতে কাজ",
    quickLinks: "দ্রুত লিংক",
    reportsAndStudies: "রিপোর্ট ও গবেষণা",
    contactInfo: "যোগাযোগের তথ্য",
    governmentOfIndia: "ভারত সরকার",
    copyright: "কপিরাইট",
    allRightsReserved: "সর্বস্বত্ব সংরক্ষিত",
    privacyPolicy: "গোপনীয়তা নীতি",
    termsOfService: "সেবার শর্তাবলী",
    addressLine1: "দক্ষতা উন্নয়ন ও উদ্যোক্তা মন্ত্রণালয়",
    addressLine2: "শ্রম শক্তি ভবন, নতুন দিল্লি - ১১০০০১",
    email: "ইমেইল",
    phone: "ফোন",
    report1: "জাতীয় দক্ষতার ব্যবধান বিশ্লেষণ রিপোর্ট ২০২৪",
    report2: "ভারতের জন্য ডিজিটাল দক্ষতার কাঠামো",
    report3: "শিল্প প্রস্তুতি মূল্যায়ন সমীক্ষা",
    report4: "প্রশিক্ষণ কর্মসূচির কার্যকারিতা অধ্যয়ন",
    report5: "কর্মসংস্থানের ফলাফল ও প্রভাব রিপোর্ট"
  },
  tamil: {
    portalName: "இந்தியாவின் தேசிய வலைத்தளம்",
    skillBridge: "ஸ்கில் பிரிட்ஜ்",
    welcome: "ஸ்கில் பிரிட்ஜ்க்கு வரவேற்கிறோம்",
    description: "இது முக்கிய உள்ளடக்கப் பகுதி. மேலே உள்ள ஹெடர் ஸ்கில் பிரிட்ஜ் லோகோ மற்றும் பிராண்டிங்கை காட்டுகிறது.",
    tryFontSize: "எழுத்துரு அளவு மாற்றத்தைக் காண ஹெடரின் மேல் வலதுபுறத்தில் உள்ள பல்வேறு A பொத்தான்களைக் கிளிக் செய்யவும்.",
    sitemap: "தளவரைபடம்",
    skipToMain: "முக்கிய உள்ளடக்கத்திற்குச் செல்லவும்",
    aboutUs: "எங்களைப் பற்றி",
    internshipOpportunities: "இந்தியாவின் இந்து அவசரங்கள்",
    mentorshipConnect: "மேன்டர்ஷிப் சேர்க்கும்",
    myMatches: "என் மேற்கொள்ளும் முடிவுகள்",
    profile: "வடிவைப்பு",
    cooperativeFederalism: "கூட்டுறவு கூட்டாட்சி",
    competitiveFederalism: "போட்டி கூட்டாட்சி",
    keyInitiatives: "முக்கிய முயற்சிகள்",
    divisions: "பிரிவுகள்",
    publications: "வெளியீடுகள்",
    disclosuresRTI: "வெளிப்பாடுகள் & RTI",
    workAtNiti: "நீதியில் வேலை",
    quickLinks: "விரைவு இணைப்புகள்",
    reportsAndStudies: "அறிக்கைகள் & ஆய்வுகள்",
    contactInfo: "தொடர்பு தகவல்",
    governmentOfIndia: "இந்திய அரசாங்கம்",
    copyright: "காப்புரிமை",
    allRightsReserved: "னைத்து உரிமைகளும் பாதுகாக்கப்பட்டுள்ளன",
    privacyPolicy: "தனியுரிமைக் கொள்கை",
    termsOfService: "சேவை நிபந்தனைகள்",
    addressLine1: "திறன் மேம்பாடு மற்றும் தொழில்முனைவு அமைச்சகம்",
    addressLine2: "ஸ்ரம் சக்தி பவன், புதுடில்லி - 110001",
    email: "மின்னஞ்சல்",
    phone: "தொலைபேசி",
    report1: "தேசிய திறன் இடைவெளி பகுப்பாய்வு அறிக்கை 2024",
    report2: "இந்தியாவிற்கான டிஜிட்டல் திறன் கட்டமைப்பு",
    report3: "தொழில்துறை தயார்நிலை மதிப்பீட்டு கணக்கெடுப்பு",
    report4: "பயிற்சி திட்ட செயல்திறன் ஆய்வு",
    report5: "வேலைவாய்ப்பு முடிவுகள் மற்றும் தாக்க அறிக்கை"
  },
  telugu: {
    portalName: "భారతదేశ జాతీయ పోర్టల్",
    skillBridge: "స్కిల్ బ్రిడ్జ్",
    welcome: "స్కిల్ బ్రిడ్జ్‌కు స్వాగతం",
    description: "ఇది ప్రధాన కంటెంట్ ప్రాంతం. పైన ఉన్న హెడర్ స్కిల్ బ్రిడ్జ్ లోగో మరియు బ్రాండింగ్‌ను ప్రదర్శిస్తుంది.",
    tryFontSize: "ఫాంట్ సైజ్ మార్పును చూడటానికి హెడర్ టాప్ రైట్‌లోని వివిధ A బటన్‌లపై క్లిక్ చేయండి.",
    sitemap: "సైట్‌మ్యాప్",
    skipToMain: "ప్రధాన కంటెంట్‌కు వెళ్లండి",
    aboutUs: "మా గురించి",
    internshipOpportunities: "ఇన్టర్న్షిప్ అవసరాలు",
    mentorshipConnect: "మేషిప్ సంబంధం",
    myMatches: "నేను మేషిప్ మేషిప్",
    profile: "ప్రొఫైల్",
    cooperativeFederalism: "సహకార సమాఖ్యవాదం",
    competitiveFederalism: "పోటీ సమాఖ్యవాదం",
    keyInitiatives: "ముఖ్య కార్యక్రమాలు",
    divisions: "విభాగాలు",
    publications: "ప్రచురణలు",
    disclosuresRTI: "వెల్లడిలు & RTI",
    workAtNiti: "నీతిలో పని",
    quickLinks: "క్రోడీకరణ లింకులు",
    reportsAndStudies: "ఐక్యత నివేదికలు & అధ్యయనాలు",
    contactInfo: "సంప్రదింపు సమాచారం",
    governmentOfIndia: "భారత ప్రభుత్వం",
    copyright: "కాపీ రైట్",
    allRightsReserved: "అన్ని హక్కులు కాపీ చేసినవి",
    privacyPolicy: "గోప్యతా విధానం",
    termsOfService: "సేవా నిబంధనలు",
    addressLine1: "కౌశల్ అభివృద్ధి మరియు ఉద్యమ శాఖ",
    addressLine2: "శ్రామశక్తి భవన్, న్యూఢిల్లీ - 110001",
    email: "ఇమెయిల్",
    phone: "ఫోన్",
    report1: "జాతీయ నైపుణ్యం ముగింపు నివేదిక 2024",
    report2: "దేశానికి డిజిటల్ నైపుణ్య సాధన",
    report3: "తలవణి పరిశ్రమ మరమత్తు",
    report4: "సంగ్రహం కార్యకలాపం అధ్యయనం",
    report5: "ఉద్యోగ అనుబంధం మరియు ప్రభావం నివేదిక"
  },
  marathi: {
    portalName: "भारताचे राष्ट्रीय पोर्टल",
    skillBridge: "स्किल ब्रिज",
    welcome: "स्किल ब्रिजमध्ये आपले स्वागत",
    description: "हे मुख्य सामग्री क्षेत्र आहे. वरचे हेडर स्किल ब्रिज लोगो आणि ब्रँडिंग दर्शवते.",
    tryFontSize: "फॉन्ट साइज बदल पाहण्यासाठी हेडरच्या टॉप राईटमधील वेगवेगळ्या A बटणांवर क्लिक करा.",
    sitemap: "साइटमॅप",
    skipToMain: "मुख्य सामग्रीवर जा",
    aboutUs: "आमच्याबद्दल",
    internshipOpportunities: "इंटर्नशिप अवसर",
    mentorshipConnect: "मेंटरशिप कनेक्ट",
    myMatches: "मेरे मैच",
    profile: "प्रोफाइल",
    cooperativeFederalism: "सहकारी संघराज्य",
    competitiveFederalism: "स्पर्धात्मक संघराज्य",
    keyInitiatives: "मुख्य उपक्रम",
    divisions: "विभाग",
    publications: "प्रकाशने",
    disclosuresRTI: "खुलासे आणि RTI",
    workAtNiti: "नीतीमध्ये काम",
    quickLinks: "जलद लिंक्स",
    reportsAndStudies: "अहवाल आणि अभ्यास",
    contactInfo: "संपर्क माहिती",
    governmentOfIndia: "भारत सरकार",
    copyright: "कॉपीराइट",
    allRightsReserved: "सर्व हक्क राखीव",
    privacyPolicy: "गोपनीयता धोरण",
    termsOfService: "सेवेसाठी अटी",
    addressLine1: "कौशल विकास आणि उद्योजकता मंत्रालय",
    addressLine2: "श्रम शक्ती भवन, नवी दिल्ली - 110001",
    email: "ई-मेल",
    phone: "फोन",
    report1: "राष्ट्रीय कौशल अंतर विश्लेषण रिपोर्ट 2024",
    report2: "डिजिटल कौशल फ्रेमवर्क फॉर इंडिया",
    report3: "उद्योग तयारी मूल्यांकन सर्वेक्षण",
    report4: "प्रशिक्षण कार्यक्रम प्रभावशीलता अध्ययन",
    report5: "रोजगार परिणाम आणि प्रभाव रिपोर्ट"
  },
  gujarati: {
    portalName: "ભારતનું રાષ્ટ્રીય પોર્ટલ",
    skillBridge: "સ્કિલ બ્રિજ",
    welcome: "સ્કિલ બ્રિજમાં આપનું સ્વાગત છે",
    description: "આ મુખ્ય સામગ્રી વિસ્તાર છે. ઉપરનું હેડર સ્કિલ બ્રિજ લોગો અને બ્રાન્ડિંગ બતાવે છે.",
    tryFontSize: "ફોન્ટ સાઇઝ ફેરફાર જોવા માટે હેડરના ટોપ રાઇટમાં વિવિધ A બટનો પર ક્લિક કરો.",
    sitemap: "સાઇટમેપ",
    skipToMain: "મુખ્ય સામગ્રી પર જાઓ",
    aboutUs: "અમારા વિશે",
    internshipOpportunities: "ઇન્ટર્નશિપ અનુસાર",
    mentorshipConnect: "મેન્ટરશિપ સંયોગ",
    myMatches: "મારા મેષિપ્",
    profile: "પ્રોફાઇલ",
    cooperativeFederalism: "સહકારી સંઘવાદ",
    competitiveFederalism: "સ્પર્ધાત્મક સંઘવાદ",
    keyInitiatives: "મુખ્ય પહેલ",
    divisions: "વિભાગો",
    publications: "પ્રકાશનો",
    disclosuresRTI: "ખુલાસા અને RTI",
    workAtNiti: "નીતિમાં કામ",
    quickLinks: "ઝડપથી જોડાઓ",
    reportsAndStudies: "અહેવાલ અને અભ્યાસ",
    contactInfo: "સંપર્ક માહિતી",
    governmentOfIndia: "ભારત સરકાર",
    copyright: "કોપીરાઇટ",
    allRightsReserved: "બધા હક્કો સંરક્ષિત છે",
    privacyPolicy: "ગોપનીયતા નીતિ",
    termsOfService: "સેવા શરતો",
    addressLine1: "ભારતીય નૌકાદળ અને ઉદ્યોગ મંત્રાલય",
    addressLine2: "શ્રમ શક્તિ ભાર્ગ, નવી દિલ્હી - 110001",
    email: "ઇમેલ",
    phone: "ફોન",
    report1: "રાષ્ટ્રીય ક્ષમતાના ખોટાના વિશ્લેષણ અહેવાલ 2024",
    report2: "ભારત માટે ડિજિટલ ક્ષમતા ફ્રેમવર્ક",
    report3: "ઉદ્યોગની તૈયારીનું મૂલ્યાંકન સર્વે",
    report4: "પ્રશિક્ષણ કાર્યક્રમની કાર્યક્ષમતાનું અભ્યાસ",
    report5: "રોજગારના પરિણામો અને અસરનો અહેવાલ"
  },
  kannada: {
    portalName: "ಭಾರತದ ರಾಷ್ಟ್ರೀಯ ಪೋರ್ಟಲ್",
    skillBridge: "ಸ್ಕಿಲ್ ಬ್ರಿಡ್ಜ್",
    welcome: "ಸ್ಕಿಲ್ ಬ್ರಿಡ್ಜ್‌ಗೆ ಸುಸ್ವಾಗತ",
    description: "ಇದು ಮುಖ್ಯ ವಿಷಯ ಪ್ರದೇಶ. ಮೇಲಿನ ಹೆಡರ್ ಸ್ಕಿಲ್ ಬ್ರಿಡ್ಜ್ ಲೋಗೋ ಮತ್ತು ಬ್ರ್ಯಾಂಡಿಂಗ್ ಅನ್ನು ತೋರಿಸುತ್ತದೆ.",
    tryFontSize: "ಫಾಂಟ್ ಗಾತ್ರ ಬದಲಾವಣೆಯನ್ನು ನೋಡಲು ಹೆಡರ್‌ನ ಟಾಪ್ ರೈಟ್‌ನಲ್ಲಿರುವ ವಿವಿಧ A ಬಟನ್‌ಗಳನ್ನು ಕ್ಲಿಕ್ ಮಾಡಿ.",
    sitemap: "ಸೈಟ್‌ಮ್ಯಾಪ್",
    skipToMain: "ಮುಖ್ಯ ವಿಷಯಕ್ಕು ಹೋಗಿ",
    aboutUs: "ನಮ್ಮ ಬಗ್ಗೆ",
    internshipOpportunities: "ಇನ್ಟರ್ನ್ಷಿಪ್ ಅವಸರಗಳು",
    mentorshipConnect: "ಮೇಷಿಪ್ ಸಂಬಂಧ",
    myMatches: "ನಾನು ಮೇಷಿಪ್",
    profile: "ಪ್ರೊಫೈಲ್",
    cooperativeFederalism: "ಸಹಕಾರಿ ಒక್ಕೂಟವಾದ",
    competitiveFederalism: "ಸ್ಪರ್ಧಾತ್ಮಕ ಒక್ಕೂಟವಾದ",
    keyInitiatives: "ಮುಖ್ಯ ಉಪಕ್ರಮಗಳು",
    divisions: "ವಿಭಾಗಗಳು",
    publications: "ಪ್ರಕಟಣೆಗಳು",
    disclosuresRTI: "ಬಹಿರಂಗಪಡಿಸುವಿಕೆ ಮತ್ತು RTI",
    workAtNiti: "ನೀತಿಯಲ್ಲಿ ಕೆಲಸ",
    quickLinks: "ಶೀಘ್ರ ಲಿಂಕ್ಸ್",
    reportsAndStudies: "ಅಂಗасಿದ್ಧಾಂತ ಮತ್ತು ಅಧ್ಯಯनಗಳು",
    contactInfo: "ಸಂಪರ್ಕ ಮಾಹಿತಿ",
    governmentOfIndia: "ಭಾರತ ಸರ್ಕಾರ",
    copyright: "ಕಾಪಿರೈಟ್",
    allRightsReserved: "ಎಲ್ಲಾ ಹಕ್ಕುಗಳು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ",
    privacyPolicy: "ಗೋಪ್ಯತಾ ನೀತಿಮಾಲೆ",
    termsOfService: "ಸೇವೆಯ ನಿಯಮಗಳು",
    addressLine1: "ಕೌಶಲ್ಯದ ಬೆಳವಣಿಗೆ ಮತ್ತು ಉದ್ಯೋಗ ಸಚಿವಾಲಯ",
    addressLine2: "ಶ್ರಮ ಶక್ತಿ ಭavan, ನ್ೂ ದೆಹಲಿ - 110001",
    email: "ಇಮೇಲ್",
    phone: "ದೂರವಾಣಿ",
    report1: "ರಾಷ್ಟ್ರೀಯ ನೈಪುಣ್ಯ ಕೊরತೆಯ ವಿಶ್ಲೇಷಣಾ ವರದಿ 2024",
    report2: "ಭಾರತದ ನಿಮಿತ ನೈపುಣ್ಯ ಫಲಕ",
    report3: "ಉದ್ಯಮ ತಯಾರಿ ಮೌಲ್ಯಮಾಪನ ಸಮೀಕ್ಷೆ",
    report4: "ಶಿಕ್ಷಣ ಕ��ರ್ಯಕ್ರಮದ ಪরಿಣಾಮಕಾರಿತ್ವ ಅಧ್యಯನ",
    report5: "ರೊಜಗಾರಿ ಫಲಿತಾಂಶಗಳು ಮತ್ತು ಪರಿಣಾಮ ವರದಿ"
  },
  malayalam: {
    portalName: "ഇന്ത്യയുടെ ദേശീയ പോർട്ടൽ",
    skillBridge: "സ്കിൽ ബ്രിഡ്ജ്",
    welcome: "സ്കിൽ ബ്രിഡ്ജിലേക്ക് സ്വാഗതം",
    description: "ഇത് പ്രധാന ഉള്ളടക്ക മേഖലയാണ്. മുകളിലുള്ള ഹെഡർ സ്കിൽ ബ്രിഡ്ജ് ലോഗോയും ബ്രാൻഡിംഗും കാണിക്കുന്നു.",
    tryFontSize: "ഫോണ്ട് സൈസ് മാറ്റം കാണാൻ ഹെഡറിന്റെ ടോപ്പ് റൈറ്റിലുള്ള വിവിധ A ബട്ടണുകളിൽ ക്ലിക് ചെയ്യുക.",
    sitemap: "സൈറ്റ്മാപ്പ്",
    skipToMain: "പ്രധാന ഉള്ളടക്കത്തിലേക്ക് പോകുക",
    aboutUs: "ഞങ്ങളെക്കുറിച്ച്",
    internshipOpportunities: "ഇന്ത്യയുടെ ഇന്തു അവസരങ്ങൾ",
    mentorshipConnect: "മേന്ടർഷീപ്പ് സംബന്ധം",
    myMatches: "എന്റെ മേന്ടർഷീപ്പുകൾ",
    profile: "പ്രൊഫൈൽ",
    cooperativeFederalism: "സഹകരണ ഫെഡറലിസം",
    competitiveFederalism: "മത്സര ഫെഡറിസം",
    keyInitiatives: "പ്രധാന സംരംഭങ്ങൾ",
    divisions: "വിഭാഗങ്ങൾ",
    publications: "പ്രസിദ്ധീകരണങ്ങൾ",
    disclosuresRTI: "വെളിപ്പെടുത്തലുകളും RTI",
    workAtNiti: "നീതിയിൽ ജോലി",
    quickLinks: "ക്വിക് ലിങ്കുകൾ",
    reportsAndStudies: "അക്കൗണ്ടിംഗ് റിപ്പോർട്ടുകൾ & പഠനങ്ങൾ",
    contactInfo: "സമ്പർക്ക വിവരങ്ങൾ",
    governmentOfIndia: "ഇന്ത്യയിലെ സർക്കാർ",
    copyright: "ചോദ്യകാലം",
    allRightsReserved: "എല്ലാ അതിക്രമങ്ങളും അവയവീകരവുമായിരിയ്ക്കട്ടെ",
    privacyPolicy: "സ്വകാര്യതാ നയം",
    termsOfService: "സേവാ നിബന്ധനകൾ",
    addressLine1: "കൗശല വികസന & സംരംഭശക്തിയുടെ മന്ത്രാലയം",
    addressLine2: "ശ്രദ്ധ ശക്തി ഭavanിൽ, ന്യൂ ഡൽഹി - 110001",
    email: "ഇമെയിൽ",
    phone: "ഫോൺ",
    report1: "ദേശീয় കൌശല സമ്പത്ത് പ്രക്ഷുബ്ധ റിപ്പോർട്ട് 2024",
    report2: "ഇന്ത്യക്കായി ഡിജിറ്റല് കൌശല മുണ്ടിപ്പെടുത്തുന്നത്",
    report3: "ഇന്ത്യയെന്നIndustryReadinessAssessmentSurvey",
    report4: "ഉല്ലാസം പദ്ധതി പ്രവർത്തनക്ഷമതയിലെ പഠനം",
    report5: "പ്രവൃത്തി സാദ്ധ്യത & സ്വാധീനം റിപ്പോർട്ട്"
  },
  punjabi: {
    portalName: "ਭਾਰਤ ਦਾ ਰਾਸ਼ਟਰੀ ਪੋਰਟਲ",
    skillBridge: "ਸਕਿਲ ਬ੍ਰਿਜ",
    welcome: "ਸਕਿਲ ਬ੍ਰਿਜ ਵਿੱਚ ਤੁਹਾਡਾ ਸੁਆਗਤ ਹੈ",
    description: "ਇਹ ਮੁੱਖ ਸਮੱਗਰੀ ਖੇਤਰ ਹੈ। ਉੱਪਰਲਾ ਹੈਡਰ ਸਕਿਲ ਬ੍ਰਿਜ ਲੋਗੋ ਅਤੇ ਬ੍ਰਾਂਡਿੰਗ ਦਿਖਾਉਂਦਾ ਹੈ।",
    tryFontSize: "ਫ਼ੌਂਟ ਸਾਈਜ਼ ਤਬਦੀਲੀ ਦੇਖਣ ਲਈ ਹੈਡਰ ਦੇ ਟਾਪ ਰਾਈਟ ਵਿੱਚ ਵੱਖ-ਵੱਖ A ਬਟਨਾਂ 'ਤੇ ਕਲਿੱਕ ਕਰੋ।",
    sitemap: "ਸਾਈਟਮੈਪ",
    skipToMain: "ਮੁੱਖ ਸਮੱਗਰੀ 'ਤੇ ਜਾਓ",
    aboutUs: "ਸਾਡੇ ਬਾਰੇ",
    internshipOpportunities: "ਇੱਨ੍ਟਰਨਸ਼ਿਪ ਅਵਸਰ",
    mentorshipConnect: "ਮੇਨ੍ਟਰਸ਼ਿਪ ਸੂਚਿਆਂ",
    myMatches: "ਮੇਰੇ ਮੇਨ੍ਟਰਸ਼ਿਪ",
    profile: "ਪ੍ਰੋਫਾਈਲ",
    cooperativeFederalism: "ਸਹਿਕਾਰੀ ਸੰਘਵਾਦ",
    competitiveFederalism: "ਮੁਕਾਬਲੇਬਾਜ਼ ਸੰਘਵਾਦ",
    keyInitiatives: "ਮੁੱਖ ਪਹਿਲਕਦਮੀਆਂ",
    divisions: "ਵਿਭਾਗ",
    publications: "ਪ੍ਰਕਾਸ਼ਨ",
    disclosuresRTI: "ਖੁਲਾਸੇ ਅਤੇ RTI",
    workAtNiti: "ਨੀਤੀ ਵਿੱਚ ਕੰਮ",
    quickLinks: "ਜਲਦੀ ਗਾਈਡ",
    reportsAndStudies: "ਰਿਪੋਰਟਾਂ ਅਤੇ ਅਧਿਆਨ",
    contactInfo: "ਸੰਪਰਕ ਜਾਣਕਾਰੀ",
    governmentOfIndia: "ਭਾਰਤ ਸਰਕਾਰ",
    copyright: "ਕਾਪੀਰਾਈਟ",
    allRightsReserved: "ਸਭ ਹੱਕ ਰਾਖਵਾਂ ਹਨ",
    privacyPolicy: "ਗੋਪਨੀਯਤਾ ਨੀਤੀ",
    termsOfService: "ਸੇਵਾ ਦੀਆਂ ਸ਼ਰਤਾਂ",
    addressLine1: "ਕੌਸ਼ਲ ਵਿਕਾਸ ਅਤੇ ਉਦਯੋਗਤਾ ਮੰਤਰਾਲਾ",
    addressLine2: "ਸ਼ਰਾਮ ਸ਼ਕਤੀ ਭਵਨ, ਨਵੀਂ ਦਿੱਲੀ - 110001",
    email: "ਈਮੇਲ",
    phone: "ਫੋਨ",
    report1: "ਦੇਸ਼ੀ ਨੈਪੁਨਿਆ ਦੀਆਂ ਘਾਟਾਂ ਦਾ ਰਿਪੋਰਟ 2024",
    report2: "ਡਿਜੀਟਲ ਸਕਿਲਜ਼ ਫਰੇਮਵਰਕ ਫਾਰ ਭਾਰਤ",
    report3: "ਉਦਯੋਗ ਯੋਗਤਾ ਮੂਲਾਂਕਨ ਸਰਵੇਖਣ",
    report4: "ਤਾਲੀਮ ਪ੍ਰੋਗਰਾਮ ਵਿੱਚ ਚਾਲੂਤਾ ਦੀ ਅਧਿਆਨ",
    report5: "ਰੋਜ਼ਗਾਰ ਦੇ ਨਤੀਜੇ ਅਤੇ ਪ੍ਰਭਾਵ ਰਿਪੋਰਟ"
  },
  odia: {
    portalName: "ଭାରତର ଜାତୀୟ ପୋର୍ଟାଲ",
    skillBridge: "ସ୍କିଲ ବ୍ରିଜ",
    welcome: "ସ୍କିଲ ବ୍ରିଜକୁ ସ୍ୱାଗତ",
    description: "ଏହା ମୁଖ୍ୟ ବିଷୟବସ୍ତୁ କ୍ଷେତ୍ର। ଉପରେ ଥିବା ହେଡର ସ୍କିଲ ବ୍ରିଜ ଲୋଗୋ ଏବଂ ବ୍ରାଣ୍ଡିଂ ଦେଖାଏ।",
    tryFontSize: "ଫଣ୍ଟ ସାଇଜ ପରିବର୍ତ୍ତନ ଦେଖିବାକୁ ହେଡରର ଟପ ରାଇଟରେ ଥିବା ବିଭିନ୍ନ A ବଟନଗୁଡ଼ିକୁ କ୍ଲିକ କରନ୍ତୁ।",
    sitemap: "ସାଇଟମ୍ୟାପ",
    skipToMain: "ମୁଖ୍ୟ ବିଷୟବସ୍ତୁକୁ ଯାଆନ୍ତୁ",
    aboutUs: "ଆମ ବିଷୟରେ",
    internshipOpportunities: "ଇନ୍ଟର୍ନ୍ଷିପ୍ ଅବସରଗୁଡ଼ିକ",
    mentorshipConnect: "ମେଷିପ୍ ସଂଯୋଗ",
    myMatches: "ମେଷିପ୍ ମେଷିପ୍",
    profile: "ପ୍ରୋଫାଇଲ",
    cooperativeFederalism: "ସହଯୋଗୀ ସଂघରାଜ୍ୟ",
    competitiveFederalism: "ପ୍ରତିଯୋଗିତାମୂଳକ ସଂघରାଜ୍ୟ",
    keyInitiatives: "ମୁଖ୍ୟ ପଦକ୍ଷେପ",
    divisions: "ବିଭାଗ",
    publications: "ପ୍ରକାଶନ",
    disclosuresRTI: "ପ୍ରକାଶ ଏବଂ RTI",
    workAtNiti: "ନୀତିରେ କାମ",
    quickLinks: "ଦ୍ରୁତ ଲିଙ୍କଗୁଡିକ",
    reportsAndStudies: "ରିପୋର୍ଟସ୍ ଓ ଅଧ୍ୟୟନ",
    contactInfo: "ଯୋଗାଯୋଗ ସୂଚନା",
    governmentOfIndia: "ଭାରତ ସରକାର",
    copyright: "କପିରାଇଟ",
    allRightsReserved: "ସବୁ ଅଧିକାର ସଂରକ୍ଷିତ",
    privacyPolicy: "ଗୋପନୀୟତା ନୀତି",
    termsOfService: "ସେବା ସର୍ତ୍ତାବଳୀ",
    addressLine1: "କୌଶଳ ବିକାଶ ଏବଂ ଉଦ୍ୟୋଗୀତା ମନ୍ତ୍ରଣାଳୟ",
    addressLine2: "ଶ୍ରମ ଶକ୍ତି ଭବନ, ନୂଆ ଦିଲ୍ଲୀ - 110001",
    email: "ଇମେଲ",
    phone: "ଫୋନ",
    report1: "ଜାତୀୟ କୌଶଳ ଅନ୍ତର ବିଶ୍ଳେଷଣ ରିପୋର୍ଟ 2024",
    report2: "ଭାରତ ପାଇଁ ଡିଜିଟାଲ କୌଶଳ ଗଠନ",
    report3: "ଶିଳ୍ପ ପ୍ରସ୍ତୁତି ମୂଲ୍ୟାଙ୍କନ ସର୍ଭେ",
    report4: "ତାଲିମ କାର୍ଯ୍ୟକ୍ରମ ପ୍ରଭାବଶୀଳତା ଅଧ୍ୟୟନ",
    report5: "ନିଯୁକ୍ତି ଫଳାଫଳ ଏବଂ ପ୍ରଭାବ ରିପୋର୍ଟ"
  },
  assamese: {
    portalName: "ভাৰতৰ জাতীয় পৰ্টেল",
    skillBridge: "স্কিল ব্ৰিজ",
    welcome: "স্কিল ব্ৰিজলৈ স্বাগতম",
    description: "এইটো মুখ্য বিষয়বস্তু অঞ্চল। ওপৰৰ হেডাৰে স্কিল ব্ৰিজ লগো আৰু ব্ৰেণ্ডিং দেখুৱায়।",
    tryFontSize: "ফণ্ট আকাৰ পৰিৱৰ্তন চাবলৈ হেডাৰৰ টপ ৰাইটত থকা বিভিন্ন A বুটামসমূহত ক্লিক কৰক।",
    sitemap: "ছাইটমেপ",
    skipToMain: "মুখ্য বিষয়বস্তুলৈ যাওক",
    aboutUs: "আমাৰ বিষয়ে",
    internshipOpportunities: "ইন্টার্নশিপ অনুষ্ঠান",
    mentorshipConnect: "মেন্টরশিপ সংযোগ",
    myMatches: "আমার ম্যাচ",
    profile: "প্রোফাইল",
    cooperativeFederalism: "সহযোগিতামূলক যুক্তৰাষ্ট্ৰবাদ",
    competitiveFederalism: "প্ৰতিযোগিতামূলক যুক্তৰাষ্ট্ৰবাদ",
    keyInitiatives: "মুখ্য পদক্ষেপসমূহ",
    divisions: "বিভাগসমূহ",
    publications: "প্ৰকাশনসমূহ",
    disclosuresRTI: "প্ৰকাশ আৰু RTI",
    workAtNiti: "নীতিত কাম",
    quickLinks: "দ্রুত লিংকসমূহ",
    reportsAndStudies: "প্ৰতিবেদন আৰু অধ্যয়ন",
    contactInfo: "যোগাযোগৰ তথ্য",
    governmentOfIndia: "ভাৰত চৰকাৰ",
    copyright: "কপিৰাইট",
    allRightsReserved: "সৰ্বস্বত্ব সংৰক্ষিত",
    privacyPolicy: "গোপনীয়তা নীতি",
    termsOfService: "সেৱাৰ শর্তাবলী",
    addressLine1: "দক্ষতা উন্নয়ন আৰু উদ্যোগ মন্ত্রণালয়",
    addressLine2: "শ্রম শক্তি ভবন, নতুন দিল্লি - ১১০০০১",
    email: "ইমেইল",
    phone: "ফোন",
    report1: "জাতীয় দক্ষতাৰ ব্যবধান বিশ্লেষণ প্ৰতিবেদন ২০২৪",
    report2: "ভাৰতৰ বাবে ডিজিটেল দক্ষতাৰ কাঠামো",
    report3: "উদ্যোগ প্ৰস্তুতি মূল্যাংকন সমীক্ষা",
    report4: "প্ৰশিক্ষণ কাৰ্যসূচীৰ কাৰ্যকাৰিতা অধ্যয়ন",
    report5: "কৰ্মসংস্থানৰ ফলাফল আৰু প্ৰভাৱৰ প্ৰতিবেদন"
  }
};

const languageNames: Record<Language, string> = {
  english: "English",
  hindi: "हिन्दी",
  bengali: "বাংলা",
  tamil: "தமிழ்",
  telugu: "తెలుగు",
  marathi: "मराठी",
  gujarati: "ગુજરાતી",
  kannada: "ಕನ್ನಡ",
  malayalam: "മലയാളം",
  punjabi: "ਪੰਜਾਬੀ",
  odia: "ଓଡ଼ିଆ",
  assamese: "অসমীয়া"
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('english');

  return (
    <LanguageContext.Provider value={{ language, setLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export function useTranslations() {
  const { language } = useLanguage();
  return translations[language];
}

export { languageNames };